server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    user:
      name: disabled
      password: disabled
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: identity-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: identity-service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/users/**
        - id: identity-service-users-exact
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/users
        - id: admin-service-brands
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/brands/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
        - id: pricing-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/pricing/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG